package resource

import (
	"regexp"
	"strings"
	"testing"
)

// loose fails unless src contains want, where any run of spaces in want matches any run of
// whitespace in src, so gofmt's column alignment doesn't matter.
func loose(t *testing.T, src, want string) {
	t.Helper()
	parts := strings.Fields(want)
	for i, p := range parts {
		parts[i] = regexp.QuoteMeta(p)
	}
	if !regexp.MustCompile(strings.Join(parts, `\s+`)).MatchString(src) {
		t.Errorf("missing %q in:\n%s", want, src)
	}
}

func mustRender(t *testing.T, name string, data any) string {
	t.Helper()
	src, err := renderGo(name, data)
	if err != nil {
		t.Fatal(err)
	}
	return src
}

func TestRenderModelFlat(t *testing.T) {
	src := mustRender(t, "model.go.tmpl", mustView(t, "Seminar", []string{"name:string", "lecture_hours:int", "division:ref"}, "", false))
	for _, want := range []string{
		"type ( Seminars = []Seminar Seminar struct {",
		"bun.BaseModel `bun:\"table:seminars,alias:seminars\"`",
		"UserID int64 `bun:\"user_id,notnull\" json:\"-\"`",
		"Name string `bun:\"name,notnull\" json:\"name\"`",
		"LectureHours int `bun:\"lecture_hours,notnull\" json:\"lectureHours\"`",
		"DivisionID int64 `bun:\"division_id,notnull\" json:\"divisionId\"`",
		"User *User `bun:\"rel:belongs-to,join:user_id=id\" json:\"-\"`",
		"Division *Division `bun:\"rel:belongs-to,join:division_id=id\" json:\"-\"`",
		"type SeminarRequest struct { Name string `json:\"name\"` LectureHours int `json:\"lectureHours\"` DivisionID int64 `json:\"divisionId\"` }",
		"\"Name\": zog.String().Trim().Min(1).TestFunc(maxChars(150)).Required(),",
		"\"LectureHours\": zog.Int().GTE(0),",
		"\"DivisionID\": zog.Int64().GT(0).Required(),",
		"func (r SeminarRequest) ToModel(userID int64) *Seminar { s := &Seminar{UserID: userID} r.ApplyTo(s) return s }",
		"func (r SeminarRequest) ApplyTo(s *Seminar) { s.Name = r.Name s.LectureHours = r.LectureHours s.DivisionID = r.DivisionID }",
		"var SeminarUpdatableColumns = []string{\"name\", \"lecture_hours\", \"division_id\"}",
		"func NewSeminarResponse(s *Seminar) SeminarResponse {",
		"res[i] = NewSeminarResponse(&seminars[i])",
	} {
		loose(t, src, want)
	}
}

func TestRenderModelChildImmutable(t *testing.T) {
	src := mustRender(t, "model.go.tmpl", mustView(t, "Topic", []string{"name:string"}, "Course", false))
	for _, want := range []string{
		"CourseID int64 `bun:\"course_id,notnull\" json:\"courseId\"`",
		"Course *Course `bun:\"rel:belongs-to,join:course_id=id\" json:\"-\"`",
		"type TopicRequest struct { CourseID int64 `json:\"courseId\"` Name string `json:\"name\"` }",
		"\"CourseID\": zog.Int64().GT(0).Required(),",
		"func (r TopicRequest) ToModel() *Topic { t := &Topic{CourseID: r.CourseID} r.ApplyTo(t) return t }",
		"func (r TopicRequest) ApplyTo(t *Topic) { t.Name = r.Name }",
		"var TopicUpdatableColumns = []string{\"name\"}",
		"CourseID: t.CourseID,",
	} {
		loose(t, src, want)
	}
	if strings.Contains(src, "UserID") {
		t.Error("a child has no owner column of its own")
	}
}

func TestRenderModelEnumMovable(t *testing.T) {
	src := mustRender(t, "model.go.tmpl", mustView(t, "Slot", []string{"kind:enum:lecture,lab", "starts_at:time:optional"}, "Outcome", true))
	for _, want := range []string{
		"type SlotKind string",
		"SlotKindLecture SlotKind = \"lecture\"",
		"var SlotKindValues = []string{string(SlotKindLecture), string(SlotKindLab)}",
		"Kind SlotKind `bun:\"kind,notnull\" json:\"kind\"`",
		"StartsAt *time.Time `bun:\"starts_at\" json:\"startsAt\"`",
		"Kind string `json:\"kind\"`",
		"\"Kind\": zog.String().OneOf(SlotKindValues).Required(),",
		"\"StartsAt\": zog.Ptr(zog.Time()),",
		"func (r SlotRequest) ToModel() *Slot { s := &Slot{} r.ApplyTo(s) return s }",
		"s.OutcomeID = r.OutcomeID // re-parentable: the service verifies the destination",
		"s.Kind = SlotKind(r.Kind)",
		"var SlotUpdatableColumns = []string{\"outcome_id\", \"kind\", \"starts_at\"}",
	} {
		loose(t, src, want)
	}
}

func TestRenderMigrationFlat(t *testing.T) {
	sql := renderMigration(mustView(t, "Seminar", []string{"name:string", "lecture_hours:int", "division:ref"}, "", false))
	for _, want := range []string{
		"-- +goose Up\nCREATE TABLE seminars (\n",
		"id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
		"user_id BIGINT NOT NULL,",
		"name VARCHAR(150) NOT NULL,",
		"lecture_hours INTEGER NOT NULL DEFAULT 0,",
		"division_id BIGINT NOT NULL,",
		"updated_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,",
		"CONSTRAINT seminars_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,",
		"CONSTRAINT seminars_division_id_fkey FOREIGN KEY (division_id) REFERENCES divisions (id) ON DELETE RESTRICT,",
		"CONSTRAINT seminars_lecture_hours_check CHECK (lecture_hours >= 0)\n);",
		"CREATE INDEX seminars_user_id_idx ON seminars (user_id);",
		"CREATE INDEX seminars_division_id_idx ON seminars (division_id);",
		"CREATE TRIGGER seminars_set_updated_at BEFORE UPDATE ON seminars FOR EACH ROW EXECUTE FUNCTION set_updated_at();",
		"-- +goose Down\nDROP TABLE IF EXISTS seminars;\n",
	} {
		loose(t, sql, want)
	}
}

func TestRenderMigrationEnumChild(t *testing.T) {
	sql := renderMigration(mustView(t, "Slot", []string{"kind:enum:lecture,lab", "starts_at:time:optional"}, "Outcome", true))
	for _, want := range []string{
		"-- +goose Up\nCREATE TYPE slot_kind AS ENUM ('lecture', 'lab');",
		"outcome_id BIGINT NOT NULL,",
		"kind slot_kind NOT NULL,",
		"starts_at TIMESTAMPTZ,",
		"CONSTRAINT slots_outcome_id_fkey FOREIGN KEY (outcome_id) REFERENCES outcomes (id) ON DELETE CASCADE\n);",
		"CREATE INDEX slots_outcome_id_idx ON slots (outcome_id);",
		"DROP TABLE IF EXISTS slots;\nDROP TYPE IF EXISTS slot_kind;",
	} {
		loose(t, sql, want)
	}
}

func TestRenderServiceFlat(t *testing.T) {
	src := mustRender(t, "service.go.tmpl", mustView(t, "Seminar", []string{"name:string"}, "", false))
	for _, want := range []string{
		"type SeminarsService struct { raptor.Service DB *DatabaseService }",
		"Where(\"seminars.user_id = ?\", userID).",
		"Order(\"seminars.name\", \"seminars.id\").",
		"Where(\"seminars.id = ? AND seminars.user_id = ?\", id, userID).",
		"return seminar, s.DB.HandleErrorNotFound(err, \"Seminar not found\")",
		"func (s *SeminarsService) Create(seminar *models.Seminar) error {",
		"Column(models.SeminarUpdatableColumns...).",
		"Where(\"id = ? AND user_id = ?\", seminar.ID, userID).",
		"func (s *SeminarsService) VerifyOwnership(seminarID, userID int64) error {",
	} {
		loose(t, src, want)
	}
}

func TestRenderServiceChild(t *testing.T) {
	src := mustRender(t, "service.go.tmpl", mustView(t, "Topic", []string{"name:string"}, "Course", false))
	for _, want := range []string{
		"Courses *CoursesService // the immediate parent, injected by type like DB",
		"const topicsOwnedByUser = `topics.course_id IN (SELECT id FROM courses WHERE user_id = ?)`",
		"Order(\"topics.course_id\", \"topics.name\", \"topics.id\").",
		"func (s *TopicsService) ListByCourse(courseID, userID int64) (models.Topics, error) {",
		"Where(\"topics.course_id = ?\", courseID).",
		"func (s *TopicsService) Create(topic *models.Topic, userID int64) error { if err := s.Courses.VerifyOwnership(topic.CourseID, userID); err != nil {",
		"Where(\"topics.id = ?\", topic.ID). Where(topicsOwnedByUser, userID).",
	} {
		loose(t, src, want)
	}
	if n := strings.Count(src, "VerifyOwnership(topic.CourseID"); n != 1 {
		t.Errorf("an immutable parent is verified on create only; found %d checks", n)
	}

	movable := mustRender(t, "service.go.tmpl", mustView(t, "Slot", []string{"name:string"}, "Outcome", true))
	if n := strings.Count(movable, "VerifyOwnership(slot.OutcomeID"); n != 2 {
		t.Errorf("a movable child verifies the destination on update as well; found %d checks", n)
	}
	loose(t, movable, "const slotsOwnedByUser = `slots.outcome_id IN ( SELECT outcomes.id FROM outcomes JOIN courses ON courses.id = outcomes.course_id WHERE courses.user_id = ? )`")
}

func TestRenderControllers(t *testing.T) {
	flat := mustRender(t, "controller.go.tmpl", mustView(t, "Seminar", []string{"name:string"}, "", false))
	for _, want := range []string{
		"type SeminarsController struct { raptor.Controller Auth *services.AuthService Seminars *services.SeminarsService Validation *services.ValidationService }",
		"seminars, err := c.Seminars.List(user.ID)",
		"if issues := c.Validation.SeminarSchema.Validate(&req); len(issues) > 0 {",
		"seminar := req.ToModel(user.ID)",
		"if err := c.Seminars.Create(seminar); err != nil {",
		"return ctx.Data(models.NewSeminarResponse(seminar), http.StatusCreated)",
		"seminar := &models.Seminar{ID: id} // identity from the path, state from the body",
		"return ctx.NoContent()",
	} {
		loose(t, flat, want)
	}

	child := mustRender(t, "controller.go.tmpl", mustView(t, "Topic", []string{"name:string"}, "Course", false))
	for _, want := range []string{
		"if raw := ctx.QueryParam(\"courseId\"); raw == \"\" {",
		"return errs.NewErrorBadRequest(\"Invalid courseId\")",
		"topics, err = c.Topics.ListByCourse(courseID, user.ID)",
		"topic := req.ToModel()",
		"if err := c.Topics.Create(topic, user.ID); err != nil {",
	} {
		loose(t, child, want)
	}
}
