package resource

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

//go:embed templates/*.tmpl
var templateFS embed.FS

var templates = template.Must(template.New("").ParseFS(templateFS, "templates/*.tmpl"))

// renderGo executes a Go template and gofmt's the result, so alignment is never the template's
// job and a template bug surfaces as a parse error naming the template.
func renderGo(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", err
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("%s produced invalid Go: %w\n%s", name, err, buf.String())
	}
	return string(src), nil
}

// setupMigration creates the updated_at trigger function every generated table uses.
const setupMigration = `-- +goose Up
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = current_timestamp;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- +goose Down
-- set_updated_at() stays: the tables of later migrations depend on it.
`

// renderMigration writes the database.md table template: the table with its foreign keys and
// CHECKs, an index per foreign key, and the updated_at trigger. Down drops the table and its
// enum types.
func renderMigration(v *view) string {
	type column struct{ name, def string }
	cols := []column{{"id", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"}}
	var constraints, indexes []string
	foreignKey := func(col, table, onDelete string) {
		constraints = append(constraints, fmt.Sprintf("CONSTRAINT %s_%s_fkey FOREIGN KEY (%s)\n        REFERENCES %s (id) ON DELETE %s", v.Table, col, col, table, onDelete))
		indexes = append(indexes, fmt.Sprintf("CREATE INDEX %s_%s_idx ON %s (%s);", v.Table, col, v.Table, col))
	}
	if v.Parent != nil {
		cols = append(cols, column{v.Parent.Column, "BIGINT NOT NULL"})
		foreignKey(v.Parent.Column, v.Parent.Table, "CASCADE")
	} else {
		cols = append(cols, column{"user_id", "BIGINT NOT NULL"})
		foreignKey("user_id", "users", "CASCADE")
	}
	for _, f := range v.Fields {
		cols = append(cols, column{f.Column, f.SQLType})
	}
	for _, r := range v.Refs {
		foreignKey(r.Column, r.Table, "RESTRICT")
	}
	for _, f := range v.Fields {
		if f.Check != "" {
			constraints = append(constraints, fmt.Sprintf("CONSTRAINT %s_%s_check CHECK (%s)", v.Table, f.Column, f.Check))
		}
	}
	cols = append(cols,
		column{"created_at", "TIMESTAMPTZ NOT NULL DEFAULT current_timestamp"},
		column{"updated_at", "TIMESTAMPTZ NOT NULL DEFAULT current_timestamp"})

	width := 0
	for _, c := range cols {
		width = max(width, len(c.name))
	}
	var lines []string
	for _, c := range cols {
		lines = append(lines, fmt.Sprintf("    %-*s  %s", width, c.name, c.def))
	}
	for _, c := range constraints {
		lines = append(lines, "    "+c)
	}

	var b strings.Builder
	b.WriteString("-- +goose Up\n")
	for _, e := range v.Enums {
		values := make([]string, len(e.Consts))
		for i, c := range e.Consts {
			values[i] = "'" + c.Value + "'"
		}
		fmt.Fprintf(&b, "CREATE TYPE %s AS ENUM (%s);\n\n", e.SQLType, strings.Join(values, ", "))
	}
	fmt.Fprintf(&b, "CREATE TABLE %s (\n%s\n);\n\n", v.Table, strings.Join(lines, ",\n"))
	for _, ix := range indexes {
		b.WriteString(ix + "\n")
	}
	fmt.Fprintf(&b, "\nCREATE TRIGGER %s_set_updated_at\n    BEFORE UPDATE ON %s\n    FOR EACH ROW EXECUTE FUNCTION set_updated_at();\n\n", v.Table, v.Table)
	fmt.Fprintf(&b, "-- +goose Down\nDROP TABLE IF EXISTS %s;\n", v.Table)
	for _, e := range v.Enums {
		fmt.Fprintf(&b, "DROP TYPE IF EXISTS %s;\n", e.SQLType)
	}
	return b.String()
}
